name: project-1
on:
  push:
    paths:
      - ".github/workflows/project-1.yml"
      - "project-1/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      -
        name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      -
        run: |
          poetry config --list

      -
        run: |
          pwd
