name: project-1
on:
  push:
    paths:
      - ".github/workflows/project-1.yml"
      - "project-1/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'project-1'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      -
        name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      -
        name: Setup cache
        id: cache
        uses: actions/cache@v2.1.5
        with:
          path: project-1/.venv
          key: ${{ runner.os }}-project-1-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-project-1-
            ${{ runner.os }}-

      -
        name: Install dependencies
        run: |
          poetry install
          ls -la
